name: "Deploy to hostinger";

on:
  push:
    paths:
      - "dist/**"
      
      jobs:
  - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: weather-app
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
