name: Deploy
 
on:
  push:
    paths:
      - dist/**
      
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Codes
      uses: actions/checkout@v3
      
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ secrets.HOST }}
        ssh-port: ${{ secrets.SSH_PORT }}
        remote-user: ${{ secrets.SSH_USER }}
        private-ssh-key: ${{ secrets.PRIVATE_KEY }}
        destination-path: ~weather-app
        
        
