name: Deploy
 
on:
  push:
    paths:
      - dist/**
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy test
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: deploy
        id: funny-deploy
        uses: BoatNg/funny-deploy@master
        env:
          REMOTE_HOST: "${{ secrets.HOST_IP }}"
          REMOTE_USER: "${{ secrets.SSH_USERNAME }}"
          REMOTE_PASSWORD: "${{ secrets.SSH_PASSWORD }}"
          REMOTE_PATH: "/home/www/deploy-action"
          SOURCE: "dist/"
