name: Deploy
 
on:
  push:
    paths:
      - dist/**
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy test
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: deploy
        id: funny-deploy
        uses: BoatNg/funny-deploy@master
        env:
          REMOTE_HOST: "${{ secrets.HOST_IP }}"
          REMOTE_USER: "${{ secrets.SSH_USERNAME }}"
          REMOTE_PORT: "${{ secrets.SSH_PORT }}"
          REMOTE_PASSWORD: "${{ secrets.SSH_PASSWORD }}"
          REMOTE_PATH: "/home/u426412520/domains/grant-dennison.co.uk/public_html/weather-app-canvas"
          SOURCE: "dist/"
