name: Deploy
 
on:
  push:
    paths:
      - dist/**
      
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Codes
      uses: actions/checkout@v3
      
    - name: Copy folder content recursively to remote
      uses: ArthurYdalgo/github-action-scp@release/0.8.0
      with:
        local: dist
        remote: weather-app
        host: ${{ secrets.HOST_IP }}
        PORT: ${{ secrets.PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
